-- -- Password - qwerty
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL) VALUES ('temp1', 'temp1', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'temp1@gmail.com');
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL) VALUES ('temp2', 'temp2', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'temp2@gmail.com');
-- --
INSERT INTO wallet(NAME, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Karta', 'Karta bankowa', 5000,0,false,1 );
--
INSERT INTO CATEGORY(ID_USER, CREDITS, NAME) VALUES (1, false, 'Jedzenie');
INSERT INTO CATEGORY(ID_USER, CREDITS, NAME) VALUES (2, false, 'Jedzenie');
INSERT INTO CATEGORY(ID_USER, CREDITS, NAME) VALUES (1, false, 'Rozrywka');
--
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Dom',1 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Kino',3 );

--
INSERT INTO TRANSACTION(AMOUNT, COMMENT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET) VALUES ( 20.99, 'Film-Joker', '2019-10-11', 2, 1);
INSERT INTO TRANSACTION(AMOUNT, COMMENT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET) VALUES ( 5.99, 'Zakupy', '2019-10-12', 1, 1);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET) VALUES ( 19.99,  '2019-10-13', 1, 1);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET) VALUES ( 9.99, '2019-10-14', 1, 1);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET) VALUES ( 43.75, '2019-10-15', 1, 1);

INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('TestEvent1', '2019-10-26', '2019-10-26', false, 1);
INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('TestEvent2', '2019-10-30', '2019-11-26', false, 1);
INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('TestEvent3', '2019-10-30', '2019-11-26', true, 1);