-- Password - qwerty
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL) VALUES ('temp1', 'temp1', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'temp1@gmail.com');
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL) VALUES ('temp2', 'temp2', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'temp2@gmail.com');
--
INSERT INTO wallet(NAME_WALLET, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Karta', 'Karta bankowa', 5000,0,false,1 );
INSERT INTO wallet(NAME_WALLET, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Karta', 'Karta bankowa', 5000,0,false,1 );
INSERT INTO wallet(NAME_WALLET, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Gotówka', 'Gotówka', 200 ,0,false,1 );
INSERT INTO wallet(NAME_WALLET, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Wakacje', 'Oszczędności na wakacje', 0,3000,true,2 );
--
INSERT INTO CATEGORY(ID_USER, TYPE_CATEGORY, NAME_CATEGORY) VALUES (1, false, 'Jedzenie');
INSERT INTO CATEGORY(ID_USER, TYPE_CATEGORY, NAME_CATEGORY) VALUES (2, false, 'Jedzenie');
INSERT INTO CATEGORY(ID_USER, TYPE_CATEGORY, NAME_CATEGORY) VALUES (1, false, 'Rozrywka');
--
INSERT INTO SUBCATEGORY(NAME_SUBCATEGORY, ID_CATEGORY) values ('Dom',1 );

