-- Password - qwerty
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL, ID_TRAVEL) VALUES ('temp1', 'temp1', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'testowe@gmail.com', 0);
INSERT INTO user(FIRST_NAME, LAST_NAME, PASS, EMAIL) VALUES ('temp2', 'temp2', '$2a$10$kzpD8VZM1cn5Dlmsy1Uw..eOa34VghnWkiwcjrSXlfoVxAQezGjYu', 'temp2@gmail.com');
-- --
INSERT INTO wallet(NAME, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Cash', 500,0,false,1 );
INSERT INTO wallet(NAME, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Card', 7000,0,false,1 );
INSERT INTO wallet(NAME, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Holiday', 1000 ,5000,true,1 );
INSERT INTO wallet(NAME, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Gifts', 600 ,600,true,1 );
INSERT INTO wallet(NAME, COMMENT, BALANCE, FINANCIAL_GOAL, SAVINGS, ID_USER) VALUES ('Cash', 'Gotowka', 5000,0,false,2 );



--
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Food');
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Transport');
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Clothes');
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Healthcare');
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Hobby');
INSERT INTO CATEGORY(ID_USER, NAME) VALUES (1, 'Other');

--
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Home',1 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Transport',4 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Home',5 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Home',6 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Home',6 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Restaurant',1 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Work',1 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Taxi',2 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Course',3 );
INSERT INTO SUBCATEGORY(NAME, ID_CATEGORY) values ('Inflow',6 );

-- --
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 20.99, '2020-01-01', 1, 1, true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 500, '2020-01-02', 10, 1, false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 45.99,  '2020-01-03', 2, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 70.99,  '2020-01-04', 9, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 12.99,  '2020-01-05', 2, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 33.99,  '2020-01-06', 2, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 12.99,  '2020-01-07', 2, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 55.99,  '2020-01-15', 2, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 70.99,  '2020-01-16', 9, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 9.99, '2020-01-22', 10, 3,false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 43.75, '2020-01-24', 1, 5,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 50, '2020-01-25', 10, 5,false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 60, '2020-01-26', 10, 5,false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 50, '2020-01-29', 1, 5,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 21.99, '2020-01-28', 10, 5,false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET, EXPENDITURE) VALUES ( 18, '2020-02-01', 1, 5,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 15, '2020-02-01', 1, 5,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 4700, '2020-02-02', 10, 2,false);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 30, '2020-02-02', 1, 1,true);
INSERT INTO TRANSACTION(AMOUNT, DATE_TRANSACTION, ID_SUBCATEGORY, ID_WALLET,EXPENDITURE) VALUES ( 19.99, '2020-02-03', 6, 1,true);


--
INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('Birthday', '2019-10-26', '2019-10-26', false, 1);
INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('Holiday', '2019-10-30', '2019-11-26', false, 1);
INSERT INTO EVENT(NAME, START_DATE, FINISH_DATE, OVER, ID_USER) VALUES ('Sea', '2019-10-30', '2019-11-26', true, 1);

INSERT INTO PERSON(EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, ID_USER) VALUES ('person1email@email.com', 'temp1', 'temp1', '000333444', 1);
INSERT INTO PERSON(EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, ID_USER) VALUES ('person2email@email.com', 'temp2', 'temp2', '000333444', 1);