export const GET_ERRORS = "GET_ERRORS";

export const GET_WALLETS = "GET_WALLETS";
export const GET_WALLET = "GET_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";

export const GET_EVENT = "GET_EVENT";
export const GET_EVENTS = "GET_EVENTS";

export const GET_PERSON = "GET_PERSON";
export const GET_PEOPLE = "GET_PEOPLE";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"

export const SET_CURRENT_USER = "SET_CURRENT_USER";
