export const GET_ERRORS = "GET_ERRORS";
export const GET_WALLETS = "GET_WALLETS";
export const GET_WALLET = "GET_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";

export const GET_BACKLOG = "GET_BACKLOG";
export const GET_WALLET_TRANSACTION = "GET_WALLET_TRANSACTION";
export const DELETE_WALLET_TRANSACTION = "DELETE_WALLET_TRANSACTION";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
